manufacture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staff.urls')),
    path('api/',include('staffAPI.urls')),
    path('admin/', admin.site.urls),
]

staff/urls.py
from django.urls import path

from . import views
app_name = 'staff'
urlpatterns = [
    ## home url
    path('', views.HomepageView.as_view(), name='home'),
    ## for user authentication urls
    path('account/signUp', views.SignUp.as_view(), name='sign-up'),
    path('account/signIn', views.SignIn.as_view(), name='sign-in'),
    path('account/profile', views.ProfileView.as_view(), name='profile'),
    path('account/signOut', views.logout_view, name='logout'),
    path('account/changePassword', views.ChangePasswordView.as_view(), name ='change-password'),
    path('account/<int:id>/editProfile', views.edit_profile, name ='edit-profile'),
    
    ## for staff crud urls 
    path("staff/", views.StaffView.as_view(), name="index"),
    path("staff/<int:pk>/detail", views.DetailView.as_view(), name='detail'),
    path('staff/create/', views.CreateStaff.as_view(), name= 'create-staff'),
    # path('staff/<int:pk>/update', views.update_staff, name = 'update-staff'),
    path('staff/<int:pk>/update', views.UpdateStaff.as_view(), name = 'update-staff'),
    path('staff/<pk>/delete', views.DeleteStaff.as_view(), name = 'delete-staff'),

]

staff/models.py
import uuid
from django.db import models
from django.urls import reverse

# Create your models here.
class staffInfo(models.Model):
    name = models.CharField(max_length=20, null=True)
    sex = models.CharField(max_length=6, null=True)
    age = models.IntegerField(null=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("staff:detail", args=[str(self.id)])
    
class User(models.Model):
    userName = models.CharField(max_length=20, null=False)
    def __str__(self) -> str:
        return self.userName
    email = models.EmailField(max_length=50, null=False)
    def __str__(self) -> str:
        return self.email
    password = models.CharField(max_length=8, null=False)
    def __str__(self) -> str:
        return self.password
    isActive = models.BooleanField(default=False)
    def __str__(self) -> str:
        return self.isActive

staff/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
# Create your views here.
from django.http import HttpRequest, HttpResponse,HttpResponseRedirect

from django.http import HttpResponse
from django.views import generic
from .models import staffInfo
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .form import RegistrationForm, UserLoginForm, UserChangePasswordForm, UserEditProfileForm
from django.contrib.auth.models import User


# importing modules
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User, Permission

def add_user_to_group_perm(username):
        content_type = ContentType.objects.get_for_model(staffInfo)     
        stafft_permission = Permission.objects.filter(content_type=content_type)
        for perm in stafft_permission:
            print(perm.codename, username)
            if (perm.codename == 'add_staffinfo' or perm.codename == 'delete_staffinfo' or perm.codename == 'view_staffinfo') and username == 'editor' :
                user = User.objects.get(username=username)
                permission = Permission.objects.get(codename=perm.codename)
                user.user_permissions.add(permission)
                get_user_model().objects.get(username = username)
            if (perm.codename == 'change_staffinfo' or perm.codename == 'view_staffinfo') and username == 'viewer':
                print('match this condition ::::::::::::::::::::::::::::::::::::')
                user = User.objects.get(username=username)
                permission = Permission.objects.get(codename=perm.codename)
                user.user_permissions.add(permission)
                get_user_model().objects.get(username = username)
            else:
                continue
                
                # viewer_group.permissions.add(perm)
                # creator_group.permissions.add(perm)
                # viewer_group.save()
                # creator_group.save()
        # if username == 'creator':
        #     user = User.objects.get(username=username)
        #     user.groups.add(creator_group)
        #     user.save()
        #     print(':::::::::::::::::: user ::::::::::::::',user.has_perm('staff.add_staffinfo'))
        # elif username == 'viewer':
        #     user = User.objects.get(username=username)
        #     user.groups.add(viewer_group)
        #     user.save()
        # else:
        #     user = User.objects.get(username=username)
        #     user.groups.add(viewer_group)
        #     user.groups.add(creator_group)
        #     user.save()
            
            
class HomepageView(generic.TemplateView):
    template_name = 'home.html'
#change their password and redirect to profile
class ChangePasswordView(PasswordChangeView,SuccessMessageMixin ):
    form_class = UserChangePasswordForm
    success_url = '/account/profile'
    success_message = "Successfully Changed Your Password"
    template_name = 'accounts/changePassword.html'

def edit_profile(request,id):
    instance = User.objects.get(id=id)
    form = UserEditProfileForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('staff:profile')
    return render(request, 'accounts/editProfile.html', {'form': form}) 

#sign up user with name and password
class SignUp(generic.FormView):
    template_name = 'accounts/signUp.html'
    form_class = RegistrationForm
    success_url='signIn'   
    def form_valid(self, form):
        valid = super(SignUp, self).form_valid(form)
        try:
            username = form.cleaned_data['username']
            form.save()
        except:
            print('::::error::::::')
            messages.error(self.request, "Something went wrong, please try again !.")
        return valid
    
#login new user after they sign up 
class SignIn(generic.FormView):
    template_name = 'accounts/signIn.html'
    form_class = UserLoginForm    
    success_url = settings.LOGIN_REDIRECT_URL
    def form_valid(self, form):
        try:
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(self.request, username=username, password=password)
            add_user_to_group_perm(username)
            user = User.objects.get(username=username)
            print(':::::::::::::::::: user perm ::::::::::::::',
                  user.has_perm('staff.add_staffinfo'),
                  user.has_perm('staff.change_staffinfo'),
                  user.has_perm('staff.view_staffinfo'),
                  user.has_perm('staff.delete_staffinfo'))
            login(self.request, user)
        except:
            messages.error(self.request, "Something went wrong, please try again !.")
        return super().form_valid(form)

#view user after sign up successfully
class ProfileView(generic.TemplateView):
    template_name = 'accounts/profile.html'

#log out and redirect to homepage directly
def logout_view(request):
    logout(request)
    return redirect('/')

class SignOutView(generic.TemplateView):
        def get(self, request: HttpRequest):
            try:
                logout(request)
                return redirect('/')
            except:
                messages.error(self.request, 'Something went wrong , please try again!..')
                
#view five staffs
class StaffView(LoginRequiredMixin,generic.ListView):
    login_url = settings.LOGIN_URL
    redirect_field_name = settings.LOGIN_REDIRECT_URL
    model = staffInfo
    context_object_name = 'staff_list'
    template_name = 'staff/index.html'
    ordering = 'id'
    paginate_by = 5
    def http_method_not_allowed(self, request: HttpRequest, *args, **kwargs):
        return super().http_method_not_allowed(request, *args, **kwargs)
    
    def get_queryset(self):
        print('call query:::::::::::', User.objects.get(username='creator').has_perm('staff:can_create_staff'))
        return staffInfo.objects.order_by('-id')
        

class DetailView(generic.DetailView):
    model = staffInfo
    context_object_name = 'staff_info'
    template_name = "staff/detail.html"
    # messages.success(request, message='Staff created!.')

class CreateStaff(PermissionRequiredMixin,SuccessMessageMixin,generic.CreateView):
     # specify the model for create view
    model = staffInfo
    template_name = 'staff/create_staff.html'
    permission_required = ('staff.add_staffinfo')
    # specify the fields to be displayed
    fields = ['name', 'sex', 'age']
    success_url = reverse_lazy('staff:index')
    
    def handle_no_permission(self) -> HttpResponse:
        print(self.request.path)
        return HttpResponse(content='<h1>No Permission, You can not do this action !</h1>')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, message='Staff created!.')
        return super(CreateStaff,self).form_valid(form)
        
    # def get_success_message(self, cleaned_data):
    #     return self.success_message % dict(
    #         cleaned_data,
    #         username=self.object.name,
    #     )

class UpdateStaff(PermissionRequiredMixin,generic.UpdateView): 
    # specify the model you want to use 
    login_url = "staff:prfile"
    model = staffInfo
    permission_required = ('staff.change_staffinfo')
    raise_exception = True
    permission_denied_message = "Permission Denied"
    template_name = 'staff/update_staff.html'
    # specify the fields 
    fields = [
        "name", 
        "sex"
    ] 
    success_url = reverse_lazy('staff:index')
    def handle_no_permission(self) -> HttpResponse:
        print(self.request.path)
        return HttpResponse(content='<h1>No Permission, You can not do this action !</h1>')
    
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, message='Staff updated!.')
        return HttpResponseRedirect(success_url)
  
    
class DeleteStaff(PermissionRequiredMixin,generic.DeleteView):
    model = staffInfo
    permission_required = ('staff.delete_staffinfo')
    template_name = 'staff/delete_staff.html'
    context_object_name = 'staff_deleted'
    success_url = reverse_lazy('staff:index')
    
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, message='Staff deleted!.')
        return HttpResponseRedirect(success_url)
    
    def handle_no_permission(self) -> HttpResponse:
        print(self.request.path)
        return HttpResponse(content='<h1>No Permission, You can not do this action !</h1>')



# class MyForm(forms.ModelForm):
# #     class Meta:
# #         model = staffInfo
# #         fields = ['name', 'sex', 'age']

# # def update_staff(request,id):
# #     instance = staffInfo.objects.get(id=id)
# #     form = MyForm(request.POST or None, instance=instance)
# #     if form.is_valid():
# #         form.save()
# #         return redirect('staff:index')
# #     # else:
# #     #     raise ValidationError(message="Error update!!")
#     return render(request, 'staff/update_staff.html', {'form': form}) 

staff/templates/accounts/changePassword.html
{%extends 'base.html'%} {%load static%} {%block title%} Change password
{%endblock%} {%block content%}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/changePassword.css' %}"
/>
<div class="row">
  <h2>Change your password here :</h2>
  <div class="col-md-8 col-sm-10 col-12">
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <div class="action">
        <button type="submit" class="btn btn-success">Change</button>
        <a href="{%url 'staff:profile'%}">Cancel</a>
      </div>
    </form>
  </div>
</div>
{%endblock%}

staff/templates/accounts/editProfile.html
{%extends 'base.html'%} {%load static%} {%block title%} Change password
{%endblock%} {%block content%}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/changePassword.css' %}"
/>
{%if user.is_authenticated%}
<div class="row">
  <h3>You are log in as {{user.username}}:</h3>
  <span>We are recommend to use an existing one.</span>
  <div class="col-md-8 col-sm-10 col-12">
    <form method="POST">
      {% csrf_token %} {{form.username }}
      <div class="action">
        <button type="submit" class="btn btn-success">Change</button>
        <a href="{%url 'staff:profile'%}">Cancel</a>
      </div>
    </form>
  </div>
</div>
{%endif%} {%endblock%}

staff/templates/accounts/profile.html
{% extends "base.html" %} {%load static %} {% block title %}User Profile
{%endblock %} {% block content%}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/profile.css' %}"
/>
<div class="container">
  {% if user.is_authenticated %}
  <h2>Hi {{ user.username }}! you have id {{user.id}}</h2>
  <div class="subContainer">
    <form action="{% url 'staff:logout' %} " method="post">
      {% csrf_token %}
      <div class="action">
        <button type="submit">Log Out</button>
      </div>
    </form>
    <form action="{% url 'staff:change-password' %} " method="post">
      {% csrf_token %}
      <div class="action">
        <button type="submit">Chang Password</button>
      </div>
    </form>
    <form action="{%url 'staff:edit-profile' user.id%} " method="post">
      {% csrf_token %}
      <div class="action">
        <button type="submit">Edit your profile</button>
      </div>
    </form>
    <form action="{%url 'staff:index'%} " method="GET">
      <div class="action">
        <button type="submit">View staff</button>
      </div>
    </form>
  </div>
  {% else %}
  <p>You are not logged in</p>
  <a href="{% url 'staff:sign-up' %}">Log In</a>
  {% endif %} {%endblock%}
</div>

staff/templates/accounts/signIn.html
{%extends 'base.html'%} {%load static%} {%block title%} Sign Up {%endblock%}
{%block content%}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/signIn.css' %}"
/>
<div class="row">
  <h2>Sign in to your account here</h2>
  <div class="col-md-8 col-sm-10 col-12">
    <form method="POST" autocomplete>
      {% csrf_token %} {{ form.as_p }}
      <div class="action">
        <button type="submit" class="btn btn-success">Log In</button>
        <span
          >Have no account ? <a href="{%url 'staff:sign-up'%}">Sign Up</a></span
        >
      </div>
    </form>
  </div>
</div>
{%endblock%}

staff/templates/accounts/signOut.html
<p>Are u sure to log out ?</p>
<form action="{% url 'staff:home' %}" method="post">
  {% csrf_token %}
  <button type="submit">Yes</button>
</form>

staff/templates/accounts/signUp.html
{%extends 'base.html'%} {%load static%} {%block title%} Sign Up {%endblock%}
{%block content%}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'accounts/signUp.css' %}"
/>
<div class="row">
  <h2>Sign up your account here</h2>
  <div class="col-md-8 col-sm-10 col-12">
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <div class="action">
        <button type="submit" class="btn btn-success">Sign up</button>
        <span
          >Alread have account ?
          <a href="{%url 'staff:sign-in'%}">Sign In</a></span
        >
      </div>
    </form>
  </div>
</div>
{%endblock%}